[package]
name = "simdly"
version = "0.1.0"
edition = "2021"

[lib]
name = "simdly"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
simdly = { path = "../../.." }
numpy = "0.21"