[package]
name = "simdly"
version = "0.1.4"
edition = "2021"

authors = ["Mahdi Tantaoui <mohamedalmahdi.tantaoui@gmail.com>"]
description = " 🚀 High-performance Rust library leveraging SIMD and Rayon for fast computations."
rust-version = "1.77"
license = "MIT"
repository = "https://github.com/mtantaoui/simdly"
documentation = "https://docs.rs/simdly/"
readme = "README.md"
keywords = ["math", "SIMD", "functions", "performance",  "Numerical"]



[profile.release]
lto = "fat" 
codegen-units = 1
