[package]
name = "simdly"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.6.0"
ndarray = "0.16.1"


[[bench]]
name = "add"
harness = false

[profile.release]
lto = "fat" # Or "thin"
codegen-units = 1
