[package]
name = "simdly"
version = "0.1.1"
edition = "2021"

authors = ["Mahdi Tantaoui <mohamedalmahdi.tantaoui@gmail.com>"]
description = " 🚀 High-performance Rust library leveraging SIMD and Rayon for fast computations."
rust-version = "1.77"
license = "MIT"
repository = "https://github.com/mtantaoui/simdly"
documentation = "https://docs.rs/simdly/"
readme = "README.md"
keywords = ["math", "SIMD", "functions", "performance",  "Numerical"]

[dependencies]
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.6.0"
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
rand = "0.9.1"

[[bench]]
name = "f32"
harness = false

[profile.release]
lto = "fat" 
codegen-units = 1
