name: Rust CI and Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Since you can't use actions/checkout, you'll need an internal version or use git commands directly
      - name: Checkout code
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch
          git checkout -f ${{ github.sha }}

      # Install Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Run tests
      - name: Run tests
        run: |
          cargo build --verbose
          cargo test --verbose

      # Format code
      - name: Format code
        run: |
          rustup component add rustfmt
          cargo fmt --all --check

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATE_TOKEN}
        env:
          CRATE_TOKEN: ${{ secrets.CRATE_TOKEN }}
